version: "3"
services:
  mygraphqldb:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - mygraphqldata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  mygraphqldata:
